### ISSUE TITLE
Cannot connect to salesforce error

### ISSUE THREAD

**Issue by ThoughtSoup** [rtCamp/gravityforms-sfmc-data-extension#2]
Hello, great plugin.

I am receiving the below error from gravity forms after following the installation instructions.

Any suggestions on how to troubleshoot the connection error?  Thank you.

Error Details
--
Date: | May 4, 2023 13:41:25
Errors: | Status: Error Message: Cannot connect to Salesforce

**Comment by prasadnevase** [comment]
Closing this issue since there had been no response since long.
