### ISSUE TITLE
Issue connecting to SFMC

### ISSUE THREAD

**Issue by reznik108** [rtCamp/gravityforms-sfmc-data-extension#5]
Hi Team, 

We have installed your app https://github.com/rtCamp/gravityforms-sfmc-data-extension however, whenever we try to submit we get the following error (see attached) I wonder if you could assist?

![photo_2024-01-01_19-00-27](https://github.com/rtCamp/gravityforms-sfmc-data-extension/assets/19213833/aa507fd0-c618-43cb-99a6-2bdef4442e58)
 Cheers

**Comment by kiranpotphode** [comment]
Please use `SFMC Field Key` of the email field from any one of the following.

- SubscriberKey
- ContactKey
- EmailAddress

Let us know if that resolves the issue.

**Comment by reznik108** [comment]
We have tried that, but to no avail :( 

We have a very basic structure 

First name
Last name
Email

Thanks
![Uploading Screenshot 2024-01-03 at 3.59.52 AM.png…]()

**Comment by prasadnevase** [comment]
May we know which key is defined as ContactKey in your SFMC data extension?

Can you please share the screenshot of the Data Extension definition from SFMC?

**Comment by reznik108** [comment]
here are the screenshots and details: 

![photo_2024-01-07_22-31-46](https://github.com/rtCamp/gravityforms-sfmc-data-extension/assets/19213833/c41da141-62f4-46d2-b77f-899d5c961e75)
<img width="1398" alt="Screenshot 2024-01-08 at 12 28 44 AM" src="https://github.com/rtCamp/gravityforms-sfmc-data-extension/assets/19213833/650b0739-5b42-4f26-b06f-f09ad1c6600b">

**Comment by reznik108** [comment]
Hey Team, can you help?
